lchs:
  config:
    # What blocks can be hidden switches
    usable-blocks: 1,2,3,4,5,7,17,22,24,35,41,42,43,45,47,48,49,53,57,67,80,82,87,88,98,108,109,110,114,121

    # Is the username checking case sensitive?
    case-sensitive-names: false

    # For different languages
    language-file: eng.yml
        
    # Send debug messages to the console?
    debug: false
        
  signcontrol:
    # Allow sign control?
    allow-signs: true

    # What trigger should HiddenSwitch look for? Default:[lchs]
    sign-text: '[lchs]'

    # Item Lock Override
    ##
    # Specify an item id here that all hidden switches will require to function.
    ##
    # 0 = Override Disabled, otherwise
    # ## = id of the global key item
    item-lock-override: 0

    # Username Shortcut
    ##
    # Allows players to type <username-shortcut> on the second line of a
    # sign to auto set their name to the sign
    ##
    # Allow username shortcut?
    allow-username-shortcut: false
        
    # Username Shortcut word
    username-shortcut: 'me'

  # Command based hidden switches
  dbcontrol:
    # Allow command based switches (WARNING!! HAS NOT BEEN FULLY TESTED)
    allow-db: false
        
    # Autosave interval
    ##
    # How many HiddenSwitch block changes (ie creating or destroying a KeyBlock)
    # should happen before saving to the database?
    #
    # If hiddenswitches get used a lot set this to a higher number, if it is used
    # rarely it would be better to set this to a lower number.
    ##
    # 0 = disable (HIDDENSWITCH WILL NOT AUTOSAVE ANY COMMAND BASED SWITCHES IF DISABLED)
    autosave: 5